OUTPUT_COLUMNS = [
    {"position": 0, "name": "代碼"},
    {"position": 1, "name": "類型"},
    {"position": 2, "name": "貨號"},
    {"position": 3, "name": "名稱"},
    {"position": 4, "name": "已發佈"},
    {"position": 5, "name": "是特色商品？"},
    {"position": 6, "name": "目錄的可見度"},
    {"position": 7, "name": "簡短內容說明"},
    {"position": 8, "name": "描述"},
    {"position": 9, "name": "折扣價開始日期"},
    {"position": 10, "name": "折扣價結束日期"},
    {"position": 11, "name": "稅金狀態"},
    {"position": 12, "name": "稅率類別"},
    {"position": 13, "name": "有庫存？"},
    {"position": 14, "name": "庫存"},
    {"position": 15, "name": "低庫存量"},
    {"position": 16, "name": "允許無庫存下單嗎？"},
    {"position": 17, "name": "單獨銷售?"},
    {"position": 18, "name": "重量 (公斤)"},
    {"position": 19, "name": "長 (公分)"},
    {"position": 20, "name": "寬 (公分)"},
    {"position": 21, "name": "高 (公分)"},
    {"position": 22, "name": "允許客戶評論嗎？"},
    {"position": 23, "name": "購買備註"},
    {"position": 24, "name": "特價"},
    {"position": 25, "name": "原價"},
    {"position": 26, "name": "分類"},
    {"position": 27, "name": "標籤"},
    {"position": 28, "name": "運送類別"},
    {"position": 29, "name": "圖片"},
    {"position": 30, "name": "下載限制"},
    {"position": 31, "name": "下載點過期天數"},
    {"position": 32, "name": "上層"},
    {"position": 33, "name": "組合商品"},
    {"position": 34, "name": "追加銷售"},
    {"position": 35, "name": "交叉銷售"},
    {"position": 36, "name": "外部網址"},
    {"position": 37, "name": "按鈕文字"},
    {"position": 38, "name": "位置"},
    {"position": 39, "name": "屬性 1 名稱"},
    {"position": 40, "name": "屬性 1 值"},
    {"position": 41, "name": "屬性 1 可見"},
    {"position": 42, "name": "屬性 1 全域"},
    {"position": 43, "name": "屬性 1 預設"},
    {"position": 44, "name": "Meta: _monsterinsights_sitenote_active"},
    {"position": 45, "name": "Meta: _yoast_wpseo_primary_product_cat"},
    {"position": 46, "name": "Meta: _yoast_wpseo_content_score"},
    {"position": 46, "name": "Meta: _yoast_wpseo_estimated-reading-time-minutes"},
    {"position": 48, "name": "Meta: _yoast_wpseo_wordproof_timestamp"},
    {"position": 49, "name": "Meta: _yoast_wpseo_metadesc"},
    {"position": 50, "name": "Meta: _yoast_wpseo_focuskw"},
    {"position": 51, "name": "Meta: _yoast_wpseo_linkdex"},
]
